export const mockOpenings = [
    {
        id: 1,
        title: 'Operations Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 2,
        title: 'Compliance Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 3,
        title: 'Design Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 4,
        title: 'Marketing & PR Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 5,
        title: 'Department of Education Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 6,
        title: 'Set Decor Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 7,
        title: 'Finance Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 8,
        title: 'Technical Associate',
        department: 'Operations',
        location: 'On-site',
        applicants: 3,
    },
    {
        id: 9,
        title: 'Head of Sponsorship',
        department: 'Operations',
        location: 'On-site',
        applicants: 1,
    },
];
